[tool.poetry]
name = "toolbox"
version = "0.1.0"
description = "Common shared modules"
authors = ["Tim Camise <tcamise@gopro.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
cowsay = "^5.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
